version: "3.8"
services:
  db:
    image: postgres:15.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
volumes:
  db:
